version: 2
updates:
  - package-ecosystem: docker
    directory: misc/docker/Dockerfile
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
