on:
  push:
    tags:
      - '*'

name: Deploy
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    container: gonitro/markdown-link-check:2
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goreleaser release --config misc/goreleaser/goreleaser.yml --rm-dist
